name: Continuous integration
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "30 10 * * 5"
permissions:
  contents: read
env:
  CI: true

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        name: Setup toolchain
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Fmt
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Check
        run: cargo build

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

  docker-test:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v4
      - name: Test image build
        run: docker build .
